### ISSUE TITLE
Want to ask if there is any way to get soft subtitles?

### ISSUE THREAD

**Issue by poposhi** [pijuskri/bilibili-caption-project#1]
Many videos have soft subtitles in Chinese, and I want to write a project that can translate Chinese soft subtitles into English, but I don't know how to get the automatically generated soft subtitles

**Comment by pijuskri** [comment]
I explicitly made this to perform ocr on hard subtitles. BiliBili only recently added soft subtitles if I remember correctly. Heres some sources I found while working on the project that could help:

- https://github.com/AdvMaple/bilibili-subtitle-download-plugin/tree/feature (for downloading subtitles)
- https://github.com/martindbp/lazybug (already existing tool that does offline soft and hard subtitle translation)

**Comment by poposhi** [comment]
Thank you very much for the useful information
